# -*- coding: utf-8 -*-
"""anomX_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I5N6MyCl1O0j1ObzfdzFTh3SeWws-FWp
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report

'''f1=pd.read_csv('/content/processed_sensor_data_FD001.csv')
f2=pd.read_csv('/content/processed_sensor_data_FD002.csv')
f3=pd.read_csv('/content/processed_sensor_data_FD003.csv')
f4=pd.read_csv('/content/processed_sensor_data_FD004.csv')'''

#print(f2.head(3))

'''df=pd.concat([f1,f2,f3,f4])
df'''

df=pd.read_csv('processed_data.csv')
df

df.info()

df.describe()

y=(df['demo_rul']<15).astype(int)
y.groupby(y).count()

df['failure'] = (df['demo_rul'] <= 15).astype(int)

engines = df['engine_id'].dropna().unique()
np.random.seed(42)
np.random.shuffle(engines)

train_size = int(len(engines) * 0.7)
train_engines = engines[:train_size]
test_engines = engines[train_size:]

train_df = df[df['engine_id'].isin(train_engines)]
test_df = df[df['engine_id'].isin(test_engines)]

drop_cols = ['id', 'raw_id', 'source_file', 'processed_at', 'demo_rul','engine_id','failure']
x_train=train_df.drop(drop_cols, axis=1)
y_train=train_df['failure']
x_test=test_df.drop(drop_cols, axis=1)
y_test=test_df['failure']

test_df.columns

rf_model = RandomForestClassifier(random_state=42, n_estimators=100, n_jobs=-1)
rf_model.fit(x_train, y_train)
rf_preds = rf_model.predict(x_test)

xgb_model = XGBClassifier(random_state=42, eval_metric='logloss')
xgb_model.fit(x_train, y_train)
xgb_preds = xgb_model.predict(x_test)

metrics = {
    'Random Forest': {
        'Precision': precision_score(y_test, rf_preds),
        'Recall': recall_score(y_test, rf_preds),
        'Accuracy': accuracy_score(y_test, rf_preds)
    },
    'XGBoost': {
        'Precision': precision_score(y_test, xgb_preds),
        'Recall': recall_score(y_test, xgb_preds),
        'Accuracy': accuracy_score(y_test, xgb_preds)
    }
}

print(classification_report(y_test, rf_preds))

print(classification_report(y_test, xgb_preds))

